package com.myspace.contentintegration;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Customer")
@org.kie.api.definition.type.Description("Customer")
public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "customer")
	private java.lang.String customer_name;
	private java.lang.Integer customer_age;
	private java.lang.String customer_docname;

	public Customer() {
	}

	public java.lang.String getCustomer_name() {
		return this.customer_name;
	}

	public void setCustomer_name(java.lang.String customer_name) {
		this.customer_name = customer_name;
	}

	public java.lang.Integer getCustomer_age() {
		return this.customer_age;
	}

	public void setCustomer_age(java.lang.Integer customer_age) {
		this.customer_age = customer_age;
	}

	public java.lang.String getCustomer_docname() {
		return this.customer_docname;
	}

	public void setCustomer_docname(java.lang.String customer_docname) {
		this.customer_docname = customer_docname;
	}

	public Customer(java.lang.String customer_name,
			java.lang.Integer customer_age, java.lang.String customer_docname) {
		this.customer_name = customer_name;
		this.customer_age = customer_age;
		this.customer_docname = customer_docname;
	}

}