package com.myspace.contentintegration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public Test() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Test(java.lang.String name) {
		this.name = name;
	}

}